config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"

  authenticated :admin_user do
    root "admin#index", as: :admin_root
  end
  get "admin", to: "admin#index"

  # admin routes
  devise_for :admins
  namespace :admin do
    resources :categories
    resources :orders
    resources :products do
      resources :stocks
    end
  end

  # user routes
  resources :categories, only: [:show]
  resources :products, only: [:show]
  get "cart", to: "carts#show"
  post "checkout", to: "checkouts#create"
  get "success", to: "checkouts#success"
  get "cancel", to: "checkouts#cancel"
  post 'webhooks', to: 'webhooks#stripe'
end

app/models/order.rb
class Order < ApplicationRecord
  # enums
  enum status: [ :pending, :completed, :canceled ]
  # associations
  has_many :order_products
  has_many :products, through: :order_products
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /admin/orders or /admin/orders.json
  def index
   @pagy_pending, @pending_orders = pagy(Order.pending.order(created_at: :desc))
   @pagy_completed, @completed_orders = pagy(Order.completed.order(created_at: :desc), page_param: :page_completed)
  end

  # GET /admin/orders/1 or /admin/orders/1.json
  def show
  end

  # GET /admin/orders/new
  def new
   @order = Order.new
  end

  # GET /admin/orders/1/edit
  def edit
  end

  # POST /admin/orders or /admin/orders.json
  def create
   @order = Order.new(order_params)

    respond_to do |format|
      if@order.save
        format.html { redirect_to admin_order_url(@order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location:@order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/orders/1 or /admin/orders/1.json
  def update
    respond_to do |format|
      if@order.update(order_params)
        format.html { redirect_to admin_order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location:@order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/orders/1 or /admin/orders/1.json
  def destroy
   @order.destroy!

    respond_to do |format|
      format.html { redirect_to admin_orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
     @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:customer_email, :status, :address, :total_amount)
    end
end

app/views/admin/orders/_form.html.erb
<%= form_with(model: [:admin, order], class: "contents") do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :customer_email %>
    <%= form.text_field :customer_email, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :status %>
    <%= form.select :status, Order.statuses.keys.map{ |key| [key.humanize, key] }, selected: order.status || :inprogress, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :address %>
    <%= form.text_area :address, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :total_amount %>
    <%= form.number_field :total_amount, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/admin/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Customer email:</strong>
    <%= order.customer_email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Status:</strong>
    <%= order.status %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Address:</strong>
    <%= order.address %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Total amount:</strong>
    <%= order.total_amount %>
  </p>

 <h6>Order Products are:</h6>
  <% if order.products.any? %>
    <% order.products.each do |product| %>
      <span><%= product.name %></span>
    <% end %>
  <% else %>
    <span class="font-bold">Oops! No products have been added in this order.</span>
  <% end %>

</div>

app/views/admin/orders/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Change Order</h1>

  <%= render "form", order: @order %>

  <%= link_to "View Order", [:admin, @order], class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "<- Order List", admin_orders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/orders/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Orders" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Order List</h1>
    <%= link_to "Make order", new_admin_order_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <h2 class="font-bold">Pending Orders</h2>
  <div class="flex flex-col w-full">
    <div class="overflow-x-auto sm:mx-0.5 lg:mx-0.5">
      <div class="py-2 inline-block min-w-full">
        <div class="overflow-x-auto">
          <table class="min-w-full overflow-x-scroll">
            <thead>
              <tr>
                <th scope="col" class="text-sm font-bold text-gray-800 px-6 text-left">ID</th>
                <th scope="col" class="text-sm font-bold text-gray-800 px-6 text-left">Customer Email</th>
                <th scope="col" class="text-sm font-bold text-gray-800 px-6 text-left">Address</th>
                <th scope="col" class="text-sm font-bold text-gray-800 px-6 text-left">Billing Amount</th>
              </tr>
            </thead>
            <tbody>
              <% @pending_orders.order(created_at: :desc).each do |order| %>
                <tr class="bg-gray-50 border-b cursor-pointer" onclick="window.location='<%= admin_order_path(order) %>'">
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                    <%= order.id %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                    <%= order.customer_email %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                    <%= order.address %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                    $<%= (order.total_amount / 100.0).to_s %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%== pagy_nav(@pagy_pending) if @pagy_pending.pages > 1 %>
        </div>
      </div>
    </div>
  </div>

  <h2 class="font-bold">Completed Orders</h2>
  <div class="flex flex-col w-full">
    <div class="overflow-x-auto sm:mx-0.5 lg:mx-0.5">
      <div class="py-2 inline-block min-w-full">
        <div class="overflow-x-auto">
          <table class="min-w-full overflow-x-scroll">
            <thead>
              <tr>
                <th scope="col" class="text-sm font-bold text-gray-800 px-6 text-left">ID</th>
                <th scope="col" class="text-sm font-bold text-gray-800 px-6 text-left">Customer Email</th>
                <th scope="col" class="text-sm font-bold text-gray-800 px-6 text-left">Address</th>
                <th scope="col" class="text-sm font-bold text-gray-800 px-6 text-left">Billing Amount</th>
              </tr>
            </thead>
            <tbody>
              <% @completed_orders.order(created_at: :desc).each do |order| %>
                <tr class="bg-gray-50 border-b cursor-pointer" onclick="window.location='<%= admin_order_path(order) %>'">
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                    <%= order.id %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                    <%= order.customer_email %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                    <%= order.address %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                    $<%= (order.total_amount / 100.0).to_s %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%== pagy_nav(@pagy_completed) if @pagy_completed.pages > 1 %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Make Order</h1>

  <%= render "form", order: @order %>

  <%= link_to "<- Order List", admin_orders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/orders/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @order %>

    <%= link_to "Modify Order", edit_admin_order_path(@order), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "<- Order List", admin_orders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Cancel Order", [:admin, @order], method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>