config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"

  authenticated :admin_user do
    root "admin#index", as: :admin_root
  end
  get "admin", to: "admin#index"

  # admin routes
  devise_for :admins
  namespace :admin do
    resources :categories
    resources :orders
    resources :products do
      resources :stocks
    end
  end

  # user routes
  resources :categories, only: [:show]
  resources :products, only: [:show]
  get "cart", to: "carts#show"
  post "checkout", to: "checkouts#create"
  get "success", to: "checkouts#success"
  get "cancel", to: "checkouts#cancel"
  post 'webhooks', to: 'webhooks#stripe'
end

app/models/product.rb
class Product < ApplicationRecord
  enum status: [ :active, :inactive ]

  # active storage
  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize_to_limit: [50, 50]
  end

  # associatons
  belongs_to :category
  has_many :stocks, dependent: :destroy
  
  # Automatic deletion of join models is direct, no destroy callbacks are triggered.
  has_many :order_products
  has_many :orders, through: :order_products
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /admin/products or /admin/products.json
  def index
    if params[:query].present?
      @pagy, @products = pagy(Product.where("name LIKE ?", "%#{params[:query]}%"))
    else
      @pagy, @products = pagy(Product.all)
    end
  end

  # GET /admin/products/1 or /admin/products/1.json
  def show
  end

  # GET /admin/products/new
  def new
    @product = Product.new
  end

  # GET /admin/products/1/edit
  def edit
  end

  # POST /admin/products or /admin/products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/products/1 or /admin/products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params.reject { |key| key["images"] })
        if product_params["images"]
          product_params["images"].each do |image|
            @product.images.attach(image)
          end
        end
        format.html { redirect_to admin_product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/products/1 or /admin/products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :status, :price, :category_id, images: [])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_with(model: [:admin, product], class: "contents") do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :status %>
    <%= form.select :status, Product.statuses.keys.map{ |key| [key.humanize, key] }, selected: product.status || :active, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.number_field :price, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :images, 'Images', class: 'p-2' %>
    <% if product.images.any? %>
      <% product.images.each do |image| %>
        <%= image_tag(image, class: "w-20 h-20 inline-block m-2") %>
      <% end %>
    <% end %>
    <br>
    <%= form.file_field :images, multiple: true, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :category_id %>
    <%= form.collection_select(:category_id, Category.order(:name), :id, :name) %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/admin/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= product.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= product.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Status:</strong>
    <%= product.status %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Price:</strong>
    $<%= (product.price.zero? ? 1000 : product.price)/100.0 %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Category:</strong>
    <%= product.category&.name %>
  </p>

  <p>
  <strong class="block font-medium mb-1">Image List</strong>
  </p>
  <% if product.images.any? %>
    <% product.images.each do |image| %>
      <%= image_tag(image, class: "w-20 h-20 inline-block m-2") %>
    <% end %>
  <% else %>
    <span>Oop! No pictures available!</span>
  <% end %>
</div>

app/views/admin/products/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl"> Modify product</h1>

  <%= render "form", product: @product %>

  <%= link_to "Back to products", admin_products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/products/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice">
      <%= notice %>
    </p>
  <% end %>

  <% content_for :title, "Products" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Products</h1>
    <%= link_to "Add Product", new_admin_product_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div class="flex mt-4 flex-col md:flex-row items-start md:items-center justify-betwee w-full">
      <%= form_with url: admin_products_path, method: :get, class: "flex" do |form| %>
        <%= form.text_field :query, placeholder: "Search", class: "rounded border-gray-500 text-gray-800" %>
        <%= form.submit "Submit", class: "cursor-pointer bg-gray-500 ml-2 hover:bg-gray-600 text-white py-2 px-4 rounded" %>
      <% end %>
      <%= form_with url: admin_products_path, method: :get, class: 'flex' do |form| %>
        <%= form.submit "Clear", class: "cursor-pointer bg-gray-500 ml-2 md:ml-2 mt-2 md:mt-0 hover:bg-gray-600 text-white py-2 px-4 rounded" %>
      <% end %>
    </div>

  <div class="flex flex-col w-full">
    <div class="overflow-x-auto sm:mx-0.5 lg:mx-0.5">
      <div class="py-2 inline-block min-w-full">
        <div class="overflow-x-auto">
          <table class="min-w-full overflow-x-scroll">
            <thead>
              <tr>
                <th scope="col" class="text-sm font-bold text-gray-800 px-6 text-left">Name</th>
                <th scope="col" class="text-sm font-bold text-gray-800 px-6 text-left">Description</th>
                <th scope="col" class="text-sm font-bold text-gray-800 px-6 text-left">Price</th>
                <th scope="col" class="text-sm font-bold text-gray-800 px-6 text-left">Image</th>
              </tr>
            </thead>
            <tbody>
              <% @products.each do |product| %>
                <tr class="bg-gray-50 border-b cursor-pointer" onclick="window.location='<%= admin_product_path(product) %>'">
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                    <%= product.name %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                    <%= product.description %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                    $<%= (product.price / 100.0).to_s %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                    <%= product.images.any? ? image_tag(product.images.first, class: "w-10 h-10") : image_tag("https://via.placeholder.com/50") %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New product</h1>

  <%= render "form", product: @product %>

  <%= link_to "Back to products", admin_products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/products/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @product %>

    <div class="my-5">
    <%= link_to "View Product Stock ->", admin_product_stocks_path(@product), class: "underline font-medium" %>
    </div>

    <%= link_to "Modify Product", edit_admin_product_path(@product), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "<- Product List", admin_products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Remove Product", [:admin, @product], method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>